name: send me a joke

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  send-a-joke:
    name: Send Joke on Email And Slack
    runs-on: ubuntu-latest
    steps:
    - name: fetch-joke
      id: api
      run: |
        #!/usr/bin/env bash
        response=$(curl --location --request GET https://official-joke-api.appspot.com/jokes/random)
        echo $response
        setup=$(jq -r '.setup' <<< "${response}")
        punchline=$(jq -r '.punchline' <<< "${response}")
        echo "joke= <strong>Setup: </strong> ${setup}, <br> <strong>Punchline: </strong> ${punchline}">> $GITHUB_ENV
        echo "slackjoke=Setup: ${setup}, Punchline: ${punchline}">> $GITHUB_ENV
    - name: send mail
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: Here is your daily joke
        # email body as text
        body: Hello, <br><br> ${{ env.joke }} <br><br> Thanks, <br> Prajwal
        # comma-separated string, send email to
        to: mail2prajwal12@gmail.com
        bcc: abhi03989@gmail.com
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # set content_type to text/html:
        content_type: text/html
        # from email name
        from: Prajwal Acharya
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: "```${{ env.slackjoke }}"
        SLACK_TITLE: Daily joke 😜😝
        SLACK_COLOR: ${{ job.status }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

