name: send me a programming joke

on:
  push:
     branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

jobs:
  send-a-programming-joke:
    runs-on: ubuntu-latest
    steps:
    - name: fetch-joke
      id: api
      run: |
        response=$(curl --location --request GET https://official-joke-api.appspot.com/jokes/programming/random)
        echo $response
        setup=$(jq -r '.[0].setup' <<< "${response}")
        punchline=$(jq -r '.[0].punchline' <<< "${response}")
        echo "joke= **Setup: ** ${setup}, <br> **Punchline: ** ${punchline}">> $GITHUB_ENV
    - name: send mail
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: send me a programming joke
        # email body as text
        html_body: ${{ env.joke }}
        # comma-separated string, send email to
        to: mail2prajwal12@gmail.com
        bcc: abhi03989@gmail.com
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # set content_type to text/html:
        content_type: text/html
        # from email name
        from: Prajwal Acharya
