name: send me a programming joke

on:
  push:
     branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

jobs:
  send-a-programming-joke:
    runs-on: ubuntu-latest
    steps:
    - name: fetch-joke
      id: api
      run: |
        echo "curl --location --request GET 'https://official-joke-api.appspot.com/jokes/programming/random') | setup=jq -r '.[0].setup',punchline='.[0].punchline')" >> $GITHUB_ENV
    - name: exit here
      run: exit 1
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: send me a programming joke
        # email body as text
        body: ${{ env.setup }} <br> ${{ env.punchline }}
        # comma-separated string, send email to
        to: mail2prajwal12@gmail.com
        bcc: abhi03989@gmail.com
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # from email name
        from: Prajwal Acharya
