name: test

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run shell scirpt
        run: |
          #!/bin/bash
          echo "Hello World"
          firstJsonoObj='[]'
          response=$(curl --location --request GET 'https://apod.ellanan.com/api?date=2022-01-01')
          jq '. += ' $firstJsonoObj $response
          echo $response
          echo $firstJsonoObj
