name: test

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run shell script
        run: |
          #!/bin/bash

          startdate='2022-01-01'
          enddate='2022-01-10'
          thedate=$( date -d "$startdate" +%Y-%m-%d )
          
          while [ "$thedate" != "$enddate" ]; do
              printf 'The date is "%s"\n' "$thedate"
              thedate=$( date -d "$thedate + 1 days" +%Y-%m-%d ) # increment by one day
              response=$(curl --location --request GET 'https://apod.ellanan.com/api?date='$thedate)
              echo "$response" > "$thedate.json"
          done
          
          ls -la

