name: test

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run shell scirpt
        run: |
          #!/bin/bash
          echo "Hello World"

          startdate='2022-01-01'
          enddate='2022-01-30'
          thedate=$( date -d "$startdate" +%Y-%m-%d )

          while [ "$thedate" != "$enddate" ]; do
              printf 'The date is "%s"\n' "$thedate"
              thedate=$( date -d "$thedate + 1 days" +%Y-%m-%d ) # increment by one day

              response=$(curl --location --request GET 'https://apod.ellanan.com/api?date='$thedate)
              echo $response
          done

          jq '.[] += ${response}" extracted_data.json

          echo "$(<extracted_data.json)"